
elastic:
  restart: always
  image: amazon/opendistro-for-elasticsearch:1.2.1
  ports:
    - "9200:9200"
    - "9600:9600"
  environment:
    - "discovery.type=single-node"    
  volumes:
    - "./knn:/usr/share/elasticsearch/plugins/opendistro_knn/"
#  volumes_from:
#    - app
#  links:
#    - app:app
kibana:
  image: amazon/opendistro-for-elasticsearch-kibana:1.2.1
  ports:
    - 5601:5601
  expose:
    - "5601"
  environment:
    ELASTICSEARCH_URL: http://elastic:9200
    ELASTICSEARCH_HOSTS: https://elastic:9200
  links:
    - elastic:elastic
        